library(stringr)
library(dplyr)
library(net.security)
source("R/load_Dataframes.R")
source("R/extractInfo.R")

#extract datagrame from net.security pacage
cves <- GetDataFrame("cves")
print("[$ shuriken $] Load cves in cves dataframe")
cpes <- GetDataFrame("cpes")
print("[$ shuriken $] Load cpes in cpes dataframe")
#extract dataframes from csv files crawler
crawlerlinks <- GetScrapyLinksDataframe()
print("[$ shuriken $] Load data/crawler_links.csv in crawlerlinks dataframe")
niktovuls <-GetNiktoVulneravilitysDataframe()
print("[$ shuriken $] Load data/nikto_crawler_links.csv in niktovuls dataframe")
nmapscan <- GetNmapScanIpDataframe()
print("[$ shuriken $] Load data/nmap_crawler.csv in nmapscan dataframe")
print("[$ shuriken $] Curren functions: ")
print("[$ shuriken $]                  * GetVulneravility_fromUrlDataframe('url')")
print("[$ shuriken $]                  * GetNumberOfVuls()")
print("[$ shuriken $] Finish load enviroment")
