library(stringr)
library(dplyr)
library(tidyr)
library(rworldmap)
library(net.security)
source(load_Dataframes_path)
source(extractInfo_path)

#extract datagrame from net.security pacage
cves <- CleanCVSS_fromCVEs()
print("[$ shuriken $] Load cves dataframe from nt.security package")
cves_Shiny <- CleanCVES_Shiny()
print("[$ shuriken $] Cleam cves dataframe for Shiny app")
cpes <- GetDataFrame("cpes")
print("[$ shuriken $] Load cpes dataframe from nt.security package")
#extract dataframes from csv files crawler
crawlerlinks <- GetScrapyLinksDataframe()
print("[$ shuriken $] Load crawler_links.csv in crawlerlinks dataframe")
niktovuls <-GetNiktoVulneravilitysDataframe()
print("[$ shuriken $] Load nikto_crawler_links.csv in niktovuls dataframe")
nmapscan <- GetNmapScanIpDataframe()
print("[$ shuriken $] Load nmap_crawler.csv in nmapscan dataframe")
geoIP <- GetGeoIPDataframe()
print("[$ shuriken $] Load geoIP_crawlerIP.csv in geoIP dataframe")

print("[$ shuriken $] Curren functions: ")
print("[$ shuriken $]                  * GetVulneravilityNikto_fromUrlDataframe('url')")
print("[$ shuriken $]                  * GetVulsNMAP_fromUrlDataframe('url')")
print("[$ shuriken $]                  * GetNumberOfVuls()")
print("[$ shuriken $] Finish load enviroment")
print("[$ shuriken $] Current Dataframes: ")
print("[$ shuriken $] - cves")
print("[$ shuriken $] - cves_Shiny")
print("[$ shuriken $] - cpes")
print("[$ shuriken $] - crawlerlinks")
print("[$ shuriken $] - niktovuls")
print("[$ shuriken $] - nmapscan")
print("[$ shuriken $] - geoIP")